export default function PrivacyPolicyPage() {
  return (
    <div className="static-page">
      <div className="static-page__inner static-page__inner--narrow">
        <h1 className="static-page__title">Privacy Policy</h1>
        <p className="static-page__meta">Last updated: January 1, 2026</p>
        <section className="static-page__section">
          <h2>1. Information We Collect</h2>
          <p>We collect information you provide directly (name, email, payment details) and information generated by your use of the service (form submissions, usage logs, device data).</p>
        </section>
        <section className="static-page__section">
          <h2>2. How We Use Your Information</h2>
          <p>We use your information to provide and improve the service, process payments, send transactional emails, and comply with legal obligations. We do not sell your personal data.</p>
        </section>
        <section className="static-page__section">
          <h2>3. Data Retention</h2>
          <p>We retain your data for as long as your account is active or as needed to provide services. You may request deletion at any time by contacting ravidarshan@formforge.in.</p>
        </section>
        <section className="static-page__section">
          <h2>4. Cookies</h2>
          <p>We use essential cookies for authentication and analytics cookies to understand how the service is used. See our Cookie Policy for details.</p>
        </section>
        <section className="static-page__section">
          <h2>5. Contact</h2>
          <p>
            For privacy-related questions, contact us at 
            <strong><a href="mailto:ravidarshan@formforge.in">ravidarshan@formforge.in</a></strong>.
            </p>
        </section>
      </div>
    </div>
  );
}
